- app.js
- routes/v1/index.js
- routes/v1/layer-groups.js
- routes/v1/sources.js
- utils/build-mapbox-style.js
Use Koa's async/await compatibility to bubble errors to a general error handler
> Use error bubbling

- app.js
- routes/v1/index.js
- routes/v1/sources.js
- utils/build-mapbox-style.js
Uses Koa async / await compatibility for general error handling
> Adds sources; uses general error handling

- .github/ISSUE_TEMPLATE/Bug_report.md
- .github/ISSUE_TEMPLATE/Feature_request.md
- CONTRIBUTING.md
- ISSUE_TEMPLATE.md
- LICENSE.md
- PULL_REQUEST_TEMPLATE.md
This PR adds boilerplate repo files from `labs-starter-app`. 
- `.github/ISSUE_TEMPLATE/Bug_report.md`
- `.github/ISSUE_TEMPLATE/Feature_request.md`
- `CONTRIBUTING.md`
- `ISSUE_TEMPLATE.md`
- `LICENSE.md`
- `PULL_REQUEST_TEMPLATE.md`
Closes #31
> Boilerplate 

- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
- data/sources/zoning-map-amendments.json
- data/sources/zoning.json
- test/acceptance/routes.layer-group.test.js
Update data tables, metadata, and change supporting-zoning from carto cdn to sql
> 47 data tables and meta

- data/base/style.json
- data/layer-groups/street-direction-arrows.json
Created a layer group for street direction arrows
> Created a layer group for street direction arrows

- data/layer-groups/waterfront-access--publically-owned.json
- data/layer-groups/waterfront-access--wpaas.json
- data/sources/transportation.json
- data/sources/waterfront-access.json
- add PAWS sources and layer groups
- fix subways SQL missing sortable column
> Awes for PAWS

- data/layer-groups/waterfront-access--publicly-owned.json
- data/layer-groups/waterfront-access--wpaas.json
Layer group changes related to https://github.com/NYCPlanning/labs-waterfront-access/pull/92.
> More clearly show diff between public and private waterfront space

- data/layer-groups/boat-launches.json
- data/sources/boat-launches.json
- data/sources/ferries.json
- Create layer group for boat launches
- Use in waterfront access app
> Boat Launches layer-group

- data/sources/paws.json
Updates SQL for paws to bring in the new boolean amenity columns.
> new paws fields

- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
- data/sources/zoning-map-amendments.json
- data/sources/zoning.json
This PR {summarize the PR}
Changes Proposed:
- New Feature
- API change
- New Domain-specific language
- Refactor of existing code
Closes #{issue number(s)}
> swap out table names for oct 30 data

- data/layer-groups/nyc-pumas.json
- data/sources/admin-boundaries.json
- yarn.lock
**Add:** 
- `nyc-pumas`
**Update with new source dataset:**
- `nyc-council-districts` 
- `community-districts` 
- `ny-assembly-districts` 
- `neighborhood-tabulation-areas` 
- `neighborhood-tabulation-areas-centroids` 
- `ny-senate-districts` 
-  `boroughs`
> Update new layers

- data/layer-groups/census-blocks.json
- data/sources/admin-boundaries.json
This PR:
- adds a layer for census blocks
- fixes concatenation issues in bk_qn_mh_boundary
> Add census blocks

- data/layer-groups/neighborhood-tabulation-areas.json
> Add layer nta

- data/layer-groups/assembly-districts.json
- data/layer-groups/boroughs.json
- data/layer-groups/community-districts.json
- data/layer-groups/neighborhood-tabulation-areas.json
- data/layer-groups/ny-senate-districts.json
- data/layer-groups/nyc-council-districts.json
- data/layer-groups/nyc-pumas.json
Closes https://github.com/NYCPlanning/labs-factfinder/issues/679 (with https://github.com/NYCPlanning/labs-factfinder/pull/683)
> revise admin boundary colors with PFF crew

- data/sources/paws.json
- scripts/create-carto-aliases.sql
Updates aliases and metadata for PAWS (publicly accessible waterfront spaces) datasets in prep for 5/20 events.
> update aliases and metadata for waterfront sites datasets

- data/sources/digital-citymap.json
- data/sources/effective-flood-insurance-rate-2007.json
- data/sources/floodplains.json
- data/sources/landmark-historic.json
- data/sources/paws.json
- data/sources/preliminary-flood-insurance-rate.json
- data/sources/supporting-zoning.json
- data/sources/zoning-map-amendments.json
- test/acceptance/routes.layer-group.test.js
Add `cartodb_id AS id` to polygon features to fix highlighting tile clipping bug
Addresses #115
> 115: add ids to sources SQL for highlighting tile clipping bug

- utils/carto.js
Throw Carto's real error message
> Throw cartos error message

- data/layer-groups/building-footprints.json
- data/layer-groups/tax-lots.json
Updates tax lots and building footprints layers to fix and/or add icons for them.
> Fix tax lot legend icon - add icon for building footprints

- data/sources/pluto.json
- scripts/create-carto-aliases.sql
Updates metadata for mappluto 19v1 and SQL documentation for mappluto view creation
> mappluto 19v1

- scripts/create-carto-aliases.sql
Updating documentation of which table our view is using.
> oct 2019 community profiles data

- data/sources/pluto.json
> 196: update pluto version number to 20v5

- README.md
- data/layer-groups/assembly-districts.json
- data/layer-groups/community-districts.json
- data/layer-groups/factfinder--pumas.json
- data/layer-groups/ny-senate-districts.json
- data/layer-groups/nyc-council-districts.json
- data/layer-groups/nyc-pumas.json
- data/sources/admin-boundaries.json
- data/sources/census-geoms.json
- data/sources/digital-citymap.json
- data/sources/landmark-historic.json
- data/sources/pluto.json
- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
- data/sources/zoning-map-amendments.json
- utils/carto.js
- Match carto source names to new Data Pipeline convention
- Exclude layers outside pipeline when attaching API to staging instance
> Integrate with EDM's Data Pipeline process.

- data/layer-groups/preliminary-flood-insurance-rate-2015.json
- data/sources/admin-boundaries.json
- data/sources/digital-citymap.json
- data/sources/floodplains.json
- data/sources/pluto.json
- data/sources/preliminary-flood-insurance-rate.json
- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
Fixes [AB#2187](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2187)
> 2187 Update "updated date" metadata for various sources based on info at linked pages

- data/layer-groups/special-purpose-subdistricts.json
Fixes [AB#2940](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2940)
> Update special purpose subdistrict tooltip langauge

- data/sources/digital-citymap.json
- data/sources/pluto.json
- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
- data/sources/zoning-map-amendments.json
This PR updates the metadata for the following layers:
- Digital City Map
- Map Pluto
- Supporting Zoning
- Zoning Districts
- Zoning Map Amendments
Closes [AB#3747](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3747)
> 3747 June data update for metadata

- utils/carto.js
This PR {summarize the PR}
Changes Proposed:
- New Feature
- API change
- New Domain-specific language
- Refactor of existing code
Closes #{issue number(s)}
> Lintfix so tests pass.

- data/layer-groups/factfinder--boroughs.json
- data/layer-groups/factfinder--cdtas.json
- data/layer-groups/factfinder--cities.json
- data/layer-groups/factfinder--districts.json
- data/sources/admin-boundaries.json
This PR {summarize the PR}
Changes Proposed:
- New Feature
- API change
- New Domain-specific language
- Refactor of existing code
Closes #{issue number(s)}
> Added CDTAs, Community Districts, and Boroughs to factfinder sources.

- README.md
- app.js
- data/etl/build_choropleths.ipynb
This PR updates the geojson for the pff choropleth layers and adds a jupyter notebook that can be used to regenerate that data
- Fixes [AB#3149](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3149)
> 3149 new choropleth data

- data/sources/floodplains.json
See https://github.com/NYCPlanning/labs-zola/pull/1033 for explain
Fixes [AB#2844](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2844)
> 2844 Refactor firm filtering

- data/layer-groups/floodplain-pfirm2015.json
Fixes [AB#2844](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2844)
> 2844 Update 2015 pfirm parent tooltip

- data/etl/build_choropleths.ipynb
- data/layer-groups/floodplain-pfirm2015.json
This PR is for a release that includes updates to the jupyter notebook that generates the data for the PFF choropleths and updates the corresponding json in the choropleths source. The jupyter notebook changes update the includes queries to match the new db schema and add logic to null out non-residential NTAs
> Merge develop to master for pff choropleth deployment

- .gitignore
- app.js
- package.json
- yarn.lock
Fixes [AB#7241](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/7241)
> 7241 Upgrade node, Wire sentry, Remove Newrelic

- app.js
Fixes [AB#7241](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/7241)
> 7241 Use environment instead of app_build

- data/layer-groups/ferries.json
- data/sources/ferries.json
- data/sources/paws.json
This PR merges changes from develop into master for the 2022 Waterfront data updates. Refer to PR #279 for original changes.
> Merge 2022 Waterfront updates to master

- data/layer-groups/ferries.json
- data/sources/admin-boundaries.json
- data/sources/ferries.json
- data/sources/paws.json
Merging develop into main with 2020 NTA update
> Merge develop to main

- data/layer-groups/paper-streets.json
- data/layer-groups/stair-streets.json
- data/sources/factfinder--admin-boundaries.json
This PR merges develop to master to release work for [AB#5455](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5455) and [AB#10294](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/10294)
> Merging develop to master

- README.md
Update readme:
1) Clarify that it is not necessary to override the ports when running locally
2) Update the build_choropleths folder reference
3) Add PFF to list of dependent applications
> update readme with clarified local ports and associated applications

- data/layer-groups/street-sections.json
This PR updates the final section maps label
> Update street-sections.json to refer to maps as final section maps

- data/layer-groups/cho-greater-transit-zone.json
- data/layer-groups/cho-transit-zones.json
- data/sources/supporting-zoning.json
- schemas/layer-group.js
Reference and style layers for
City of Yes for Housing Opportunity
closes #342
> Add housing opporunity layers

- data/layer-groups/cho-transit-zones.json
Closes https://github.com/NYCPlanning/labs-zola/issues/1218
> Add plain text language to tooltips

- data/layer-groups/cho-transit-zones.json
Merges changes from #347  to master for prod release.
> Merging Transit Zones copy changes to master for prod release

- data/sources/supporting-zoning.json
Point to housing source layers that will be automatically synced going forward
closes #346
The changes are marked high priority, over changes that already exist on `develop` (node upgrades and pff data updates)
> Update housing source layers

- data/layer-groups/appendixj-designated-mdistricts.json
> Issue 354 Updated Asset Link

- data/layer-groups/appendixj-designated-mdistricts.json
Feature commit -> master
- Update hyperlinks in support of DCP homepage launch
> Release: Updated Asset Link

- data/layer-groups/zoning-map-index.json
- data/sources/supporting-zoning.json
> Issue 362 Add Zoning Map Index to API

- data/sources/supporting-zoning.json
> Issue/362 Subplan names formatting

- data/sources/supporting-zoning.json
Added `zmi_id` to carto query for use in clickable grid squares
- Closes #365
> Issue 365 Update ZMI Supporting Zoning to Enable Clickable ZMI Grid Squares

- data/layer-groups/zoning-for-accessibility.json
- data/sources/supporting-zoning.json
Added zoning for accessibility layer in api to support the ZoLa ZMI layer 
- Closes #367
> Issue 367 Add Zoning for Accessibility Layer

- data/layer-groups/zoning-for-accessibility.json
- package.json
- updated hover text for ZFA
- corrected URL for ZFA infolink
Closes #371
Closes #372
> Issues 371, 372 ZFA Feedback and Bug Fixes

- data/layer-groups/aerials.json
- data/sources/aerials-2024.json
this PR merges the new 2024 ortho to master for prod release.
> Merge 2024 ortho to master

- data/layer-groups/coastal-zone-boundary.json
- data/layer-groups/e-designations.json
- data/layer-groups/floodplain-efirm2007.json
- data/layer-groups/floodplain-pfirm2015.json
- data/layer-groups/fresh.json
- data/layer-groups/inclusionary-housing.json
- data/layer-groups/low-density-growth-mgmt-areas.json
- data/layer-groups/mandatory-inclusionary-housing.json
- data/layer-groups/transit-zones.json
- data/layer-groups/waterfront-access-plan.json
- data/sources/admin-boundaries.json
- data/sources/boat-launches.json
- data/sources/digital-citymap.json
- data/sources/factfinder--admin-boundaries.json
- data/sources/paws.json
- data/sources/pluto.json
- data/sources/supporting-zoning.json
- data/sources/zoning-districts.json
- data/sources/zoning-map-amendments.json
Update nyc.gov/planning links
- Closes #380
> 380 Update links on Layers API
