NYCPlanning/labs-layers-api

app.js, routes/v1/index.js, routes/v1/sources.js, utils/build-mapbox-style.js, utils/structure-carto-source.js
Some of our utilities were using promises and try / catch, but since Koa is a single promise chain, we can rely on bubbling to a general error handler.
=> Remove promises / trycatch

test/acceptance/routes.layer-group.test.js
If you are overriding a default in the layer-group setup, and the target value is an element in an array, you can skip elements by adding a blank array or object, depending on what type it is:
```javascript
{
'layer-groups': [
{
id: 'tax-lots',
layers: [
{
layer:
{
paint:
{
'fill-color':
{
stops:
[
[],
[
'02',
'#FFFFFF',
],
],
},
},
},
},
],
},
],
}
```
=> New test for array and object skips

test/acceptance/routes.layer-group.test.js, utils/build-mapbox-style.js
- Sets the `visibility` property on each `layer` to match the `visible` property on its layergroup.  This allows a client to request a layergroup with `visibile:false` and expect that each of that layergroup's corresponding layers will be initially set to `visibility:none`, so they will be hidden and will not request any data/tiles.
- Sets `metadata.planninglabs:layergroupid` to the id of the layergroup.  This will be useful in the frontend to manipulate all layers associated with a layergroup.
- Adds tests for both ^^
=> add metadata and visibility

data/layer-groups/aerials.json, package.json, routes/v1/layer-groups.js, routes/v1/sources.js, test/acceptance/routes.layer-group.test.js, test/validations/data.js, utils/build-mapbox-style.js, utils/structure-carto-source.js
It's (was) Friday! Let's wire this up to a real app. We learned:
- We need to serialize as JSON:API compliant
- Sources go in the meta object
- Layers don't go in the meta object
- Layers must be sideloaded in the LayerGroup response
- We have to extract each layer id from its style object which stinks
Tests included!
=> Break everything we did its friday

data/layer-groups/citymap.json, data/layer-groups/commercial-overlays.json, data/layer-groups/e-designations.json, data/layer-groups/effective-flood-insurance-rate-2007.json, data/layer-groups/floodplain-efirm2007.json, data/layer-groups/floodplain-pfirm2015.json, data/layer-groups/limited-height-districts.json, data/layer-groups/mandatory-inclusionary-housing.json, data/layer-groups/preliminary-flood-insurance-rate-2015.json, data/layer-groups/special-purpose-subdistricts.json, data/layer-groups/tax-lots.json, data/layer-groups/zoning-districts.json
Add {{{ }}} too tooltip templates to avoid HTML escape formatting for map tooltips
=> add third { to tooltip templates

README.md
This PR updates the README, replacing the placeholders from the boilerplate, and links to the Joi data schemas. Addresses #6
=> update readme, link to schemas

data/layer-groups/e-designations.json, package.json
Deleted <br>s in the e-designation tooltip as a temporary fix for https://github.com/NYCPlanning/labs-zola/issues/656
=> deleted <br>s

schemas/layer-group.js
This PR adds `filter` to the layer-group schema, allowing for layer-group-wide filters to be applied.
=> Add `filter` to layer-group schema

data/sources/paws.json
This PR expands the fields collected from the publiclyownedwaterfront table, so they can be used in a pop up in the waterfront access map.
=> add fields needed for public park popup

data/layer-groups/assembly-districts.json, data/layer-groups/boroughs.json, data/layer-groups/community-districts.json, data/layer-groups/neighborhood-tabulation-areas.json, data/layer-groups/ny-senate-districts.json, data/layer-groups/nyc-council-districts.json, data/layer-groups/nyc-pumas.json
This PR changes all the administrative boundary colors to work better with Population FactFinder. Since PFF and other apps (e.g. ZoLa) use these layer groups, all 7 files were to be adjusted not just the one referenced in the PFF issue. Closes https://github.com/NYCPlanning/labs-factfinder/issues/663.
=> New Administrative Boundaries Colors 

data/layer-groups/e-designations.json
This PR adds external link icon to template for e-designation tooltip label
Addresses issue #736, but does not close it because dot still needs to be made highlightable on hover
=> 736: Add external link to e-designation tooltip label

data/layer-groups/appendixj-designated-mdistricts.json, data/layer-groups/coastal-zone-boundary.json, data/layer-groups/e-designations.json, data/layer-groups/effective-flood-insurance-rate-2007.json, data/layer-groups/fresh.json, data/layer-groups/inclusionary-housing.json, data/layer-groups/low-density-growth-mgmt-areas.json, data/layer-groups/mandatory-inclusionary-housing.json, data/layer-groups/preliminary-flood-insurance-rate-2015.json, data/layer-groups/sidewalk-cafes.json, data/layer-groups/transit-zones.json, data/layer-groups/waterfront-access-plan.json, schemas/layer-group.js
This PR adds a `link` property as a child to the `legend` object in 12 layer-groups. These are all "supporting" layers that do not have their own profiles in zola.
Overall goal is to add "link" icons next to tooltip icons in the layer-group legend. These icons link out to an information page for the associated supporting layers. A `legend-link-icon` component will also be added to `labs-ui` so that the zola front end only requires `layerGroups.layer-name.legend.link`
=> 737: add links to legends for supporting zoning layers

data/sources/admin-boundaries.json, schemas/source.js, utils/carto.js, utils/structure-carto-source.js
This PR adds an optional `buffersize` property to source configs.  This is used when instantiating vector tiles in carto.  The default value of `buffersize.mvt` is `0` in carto's maps api.  This was causing the tile boundary to appear in mapboxgl for large polygons that span a tile boundary visualized as type `line` with a large line-width.
Once deployed, closes this issue in ZoLa: https://github.com/NYCPlanning/labs-zola/issues/774
=> add optional buffersize to source configs, send to carto

data/base/style.json
This PR adds the property `visibility` to the `building` layer on the mapboxStyle basemap. This allows for us to toggle the visibility from `visible` to `none` in the front end of Applicant Maps. 
This is so that I can add our own `building-footprints` layer-group, which allows for more specific styling depending on different maps.
=> App maps issue 83: add property for basemap mapboxStyle building visibility

data/sources/admin-boundaries.json, data/sources/boat-launches.json, data/sources/census-geoms.json, data/sources/citibike-stations.json, data/sources/digital-citymap.json, data/sources/effective-flood-insurance-rate-2007.json, data/sources/ferries.json, data/sources/floodplains.json, data/sources/landmark-historic.json, data/sources/paws.json, data/sources/preliminary-flood-insurance-rate.json, data/sources/supporting-zoning.json, data/sources/transportation.json, scripts/create-carto-aliases.sql
This PR updates Carto queries to query from aliased views of the latest dataset version. This reduces data maintenance overhead (now we only need to redefine the view when we get a new data version instead of find/replacing the table name throughout the code base) and makes this app match data view references used in all our other apps.
Closes #123.
=> use-aliased-data

data/sources/pluto.json, data/sources/supporting-zoning.json, data/sources/zoning-districts.json, data/sources/zoning-map-amendments.json, scripts/create-carto-aliases.sql
This PR updates metadata for end of March data updates. 
Aliases were updated accordingly with this SQL:
```
DROP VIEW IF EXISTS mandatory_inclusionary_housing;
CREATE VIEW mandatory_inclusionary_housing AS 
(SELECT * FROM mandatory_inclusionary_housing_v201903);
GRANT SELECT ON mandatory_inclusionary_housing TO publicuser;
DROP VIEW IF EXISTS e_designations;
CREATE VIEW e_designations AS 
(SELECT * FROM e_designations_v201903);
GRANT SELECT ON e_designations TO publicuser;
DROP VIEW IF EXISTS commercial_overlays;
CREATE VIEW commercial_overlays AS 
(SELECT * FROM commercial_overlays_v201903);
GRANT SELECT ON commercial_overlays TO publicuser;
DROP VIEW IF EXISTS limited_height_districts;
CREATE VIEW limited_height_districts AS 
(SELECT * FROM limited_height_districts_v201903);
GRANT …
```
=> march metadata updates

data/sources/pluto.json, data/sources/supporting-zoning.json
- Updates metadata for supporting zoning layers
- Updates data source for block centroid labels. EDM has created a new dataset for us called dtm_block_centroids that gets the block centroids from the DTM dataset instead of MapPLUTO.
=> end of may 2019 data updates

data/sources/supporting-zoning.json
We need to include `cartodb_id` AND `cartodb_id AS id` for special purpose districts, because the special purpose districts adapter in zola uses `cartodb_id`
=> 115: add cartodb_id as its own column in addition to cartodb_id AS id

data/sources/pluto.json, data/sources/supporting-zoning.json, data/sources/zoning-districts.json, data/sources/zoning-map-amendments.json
Add buffer to pluto, supporting zoning, zoning amendments, and zoning districts to avoid grid lines showing up on map in zola. 
```
"buffersize": {
"mvt": 10
},
```
Connected to PR #114 (where we first did this for admin boundaries)
Closes #[800](https://github.com/NYCPlanning/labs-zola/issues/800) (issue in zola)
=> 800: add buffers to source layers to avoid extra grid lines showing up on map

test/acceptance/routes.layer-group.test.js
Closes #145 by looking in the correct object for certain properties to assert for...
Unclear why these were broken in the first place, but this seems to re-align with the intent of the test...
=> Fix broken tests

test/acceptance/routes.layer-group.test.js, utils/carto.js
This PR mocks the Carto API response using Nock. These tests can be run offline and should work without requiring the API call, eliminating noise in the test environment.
This also adds a "catch" handler to the Carto utility.
Closes #22
=> Offline-ify tests by assuming Carto Works; catch error

.eslintrc, test/acceptance/routes.layer-group.test.js, test/acceptance/routes.layer-groups.error-handling.test.js, utils/carto.js
This PR addresses but does not close issue #148 - it handles an error response from Carto, and throws into the logs, so we can understand what is going on.
=> 148 slow responses

.eslintrc, app.js, package.json, test/unit/utils.structure-carto-source.test.js, utils/build-mapbox-style.js, utils/carto.js, utils/structure-carto-source.js, utils/structure-regular-source.js
Addresses #148 and #150 by squashing the number of requests to Carto one, and grouping specific layers of sources into a single URL template for each source definition.
Anecdotally this improves load times and reliability dramatically but should be tested on canary first.
=> Use one tile URL; group layers into URLs

app.js, serializers/layer-groups.js, utils/local-resources-utilities/-load-json.js, utils/local-resources-utilities/find-all.js, utils/local-resources-utilities/find.js, utils/local-resources-utilities/where.js
Addresses #155 by forcing the full database to be loaded in-memory when the app boots up. It's unclear whether this will actually improve anything because anecdotally I can say with confidence that the performance bottleneck comes from the large # of Carto maps API calls. 
Still, we should keep drilling down to see how we can make the Carto query more efficient.
=> Make json files synchronous, loaded into memory

data/sources/landmark-historic.json, data/sources/supporting-zoning.json, data/sources/zoning-districts.json, data/sources/zoning-map-amendments.json, scripts/create-carto-aliases.sql
- Updates metadata and SQL documentation for views of latest data
- Updates query for historic landmarks, since the name of a column changed slightly
All the of the views, except for the historic_districts_lpc one, have been updated on Carto already.
Once this is merged in master, we need to immediately update the view for historic landmarks. Updating it now, without the corresponding SQL changes in the data source file, breaks the ZoLa app.
```
DROP VIEW IF EXISTS historic_districts_lpc;
CREATE VIEW historic_districts_lpc AS
(SELECT * FROM historic_districts_lpc_v20190628);
GRANT SELECT ON historic_districts_lpc TO publicuser;
```
=> nov 2019 data updates

data/layer-groups/citymap.json
This PR adds specific rules for Record Streets in the `citymap` layer group, so that they're styled differently than other Unmapped Streets.
=> style record streets

.gitignore, data/layer-groups/citymap.json, data/sources/digital-citymap.json
This PR fixes the `citymap` layer group's style filters to work with the new data schema.
=> update citymap w/ new data schema

data/sources/digital-citymap.json, data/sources/landmark-historic.json, data/sources/pluto.json, data/sources/supporting-zoning.json, data/sources/zoning-districts.json, data/sources/zoning-map-amendments.json, utils/carto.js
This PR updates Layers API to work with the new EDM Data Pipeline. EDM is now uploading tables to carto with _production and _staging suffixes, and Layers API needs to target these tables. Previously Layers API targeted views named without those suffixes. 
This PR only makes updates for tables Adrien reported is ready as of 2/17. Others are yet to be updated* 
Within the `data/sources` files, this PR  parameterizes table names within sql statements using {{ENV}} placeholder. {{ENV}} will be replayed with either '_production' or '_staging' depending on the Node env. 
Fixes [AB#865](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/865)
*Other layers not yet updated:
aerials
subway lines, mta lines, (sources/transportations.json)
supporting-zoning …
=> 865 Target env-specific Carto tables,  round 1

data/layer-groups/factfinder--census-blocks.json, data/layer-groups/factfinder--districts.json, data/sources/admin-boundaries.json, data/sources/census-geoms-2020.json
This PR makes updates in preparation for updates to labs-factfinder:
- Adds new geographies for the 2020 census update to factfinder
- Updates sql queries to use the carto tables for 2020 geographies
Closes [AB#4282](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4282)
=> 4282 update sql queries with new 2020 geos

data/layer-groups/choropleths.json, data/layer-groups/community-district-tabulation-areas.json, data/layer-groups/zip-codes.json, data/sources/admin-boundaries.json
This PR adds new layers for cdtas and zipcodes
Changes Proposed:
- New json in layers-groups folder for the new overlay layers
Closes #AB4227, #AB3622
Supports/necessary for https://github.com/NYCPlanning/labs-factfinder/pull/868
=> Adding layers for zipcodes and cdta overlays

data/layer-groups/factfinder--boroughs.json, data/layer-groups/factfinder--cdtas.json, data/layer-groups/factfinder--cities.json, data/layer-groups/factfinder--districts.json, data/layer-groups/factfinder--ntas.json, data/layer-groups/factfinder--pumas.json, data/sources/admin-boundaries.json, data/sources/factfinder--admin-boundaries.json
Previously Factfinder specific Layer Groups pointed to the general admin boundary source, and changes were made to that admin boundary source. This is dangerous because the admin boundary source pointed to ad hoc Factfinder Carto layers. This can affect other apps that depend on the older, official geographies. 
This moves those changes to the admin boundary source to `factfinder--admin-boundaries`, which is specific to Factfinder. It then points PFF Layer Groups to this new PFF specific source.
- Fixes [AB#4544](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4544)
=> 4544 Point PFF-specific Layer Groups to PFF-specific Sources

data/sources/factfinder--admin-boundaries.json
The new Factfinder frontend depends on the geoid property on boroughs and cdta layers (as with all other layers). These were not included in the borough and cdta layers delievered to the frontend, thus the borough and cdta selection wasn't working. 
This PR changes the properties SELECTed on those layers to match what is in [queries/summary-levels](https://github.com/NYCPlanning/labs-factfinder/blob/develop/app/queries/summary-levels.js). Other properties are included for convenience, just in case the frontend relies on them.  
- Fixes [AB#4869](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4869)
=> 4869 Include geoid prop for PFF boroughs and cdtas

data/layer-groups/floodplain-efirm2007.json, data/layer-groups/floodplain-pfirm2015.json, data/sources/floodplains.json
Adds Shaded X (or "0.2% flood chance") values to the firm (2007) and pfirm (2015) layers.
Updates the firm and pfirm sources to use the new EDM Pipeline fema_firm and fema_pfirm carto layers.
The layers are truly a mess. There's a duplicate layers in both frontend and backend. The layer slugs are also a mess and need updating. However it requires updates to the frontend as well. 
Does not yet create separate toggles for each flood category. 
- Fixes [AB#2844](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/2844)
=> 2844 Add Shaded X zones to floodplain maps

data/layer-groups/floodplain-efirm2007.json, data/layer-groups/floodplain-pfirm2015.json, data/sources/floodplains.json
Pairs with frontend https://github.com/NYCPlanning/labs-zola/pull/1032
Accommodates the extra request to enable toggling individual flood subcategories. Please look at the last two commits in this PR for the relevant changes.
Really unfortunately, here we're building off of bad code and adding more bad code. We eventually need cleanup and rework. 
The existing pattern used for toggling Commercial Districts and Zoning Districts subcategories depends on those layer sources to have an `overlay` attribute. The frontend `layer-palette` component code will apply the same global array of filters to every layer, and the filters are based on the `overlay` attribute. So it depends on the `overlay` attribute values to be unique across layers. 
This PR adds an extra `overlay` virtual attribute to the …
=> 2844 Accommodate flood subcategory toggle

data/sources/ferries.json, data/sources/paws.json
This PR updates `ferries.json` and `paws.json` sources to point to new 2022 datasets. Not that the new queries point directly to dated Carto datasets, instead of VIews used previously. Eventually, we should move these datasets to the "new" way of doing things that doesn't use the Views at all.
=> Update ferry and waterfront queries to point to new datasets

data/sources/admin-boundaries.json
This PR updates the NTA data source to point to the new `dcp_nta_2020` dataset in Carto so that it shows 2020 NTAs, instead of 2010. As far as I can tell, the layer groups that reference this source are only used by Zola, however note that there are separate data sources and layer groups for PFF, some of which reference other NTA Carto datasets.
=> Update nta source to point to 2020 data set in Carto

data/layer-groups/paper-streets.json, data/layer-groups/stair-streets.json
Stair and paper street layers were not being displayed in NYC Streets app. The issue was that the filters for these layers no longer matched the current variable names on Carto. 
- Fixes AB[#10294](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20R?workitem=10294)
Streets App:
=> 10294 – Change stair and paper street layer filters to match variable names on Carto

data/layer-groups/e-designations.json
Part of AB[#11999](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/23B?workitem=11999). Updates e-designation tooltip template to no longer include ULURP or CEQR numbers.
Holding off on merging until the new E-Designation Info Panel is also ready.
=> 11999 – Remove ULURP and CEQR numbers from e-designation tooltips

data/layer-groups/aerials.json, data/sources/aerials-1924.json, data/sources/aerials-1951.json, data/sources/aerials-1996.json, data/sources/aerials-20012.json, data/sources/aerials-2004.json, data/sources/aerials-2006.json, data/sources/aerials-2008.json, data/sources/aerials-2010.json, data/sources/aerials-2012.json, data/sources/aerials-2014.json, data/sources/aerials-2016.json, data/sources/aerials-2018.json, data/sources/aerials-2020.json, data/sources/aerials-2022.json
Closes #333.
- Updates references to aerial layer endpoints and metadata in source layers.
- Adds new layers for 2018, 2020, 2022 aerials.
- Adds references to these new layers in aerials layer-group
=> Update aerial source layers and layer group
